import os
from dataset_keyword_generator import generate_dataset, generate_dataset_with_keywords
from query_keywords_generator import generate_query_keywords

if __name__ == "__main__":
    # generate_dataset("realworld", "AM", "out.wang-amazon", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "AM", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "AR", "out.amazon-ratings", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "AR", "keywords_list.txt", 5, 10)

    # generate_dataset_with_keywords("realworld", "BS", "out.bibsonomy-2ui", "out.bibsonomy-2ti", 1000)
    # generate_query_keywords("realworld", "BS", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "CM", "out.librec-ciaodvd-movie_ratings", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "CM", "keywords_list.txt", 5, 10)

    # generate_dataset_with_keywords("realworld", "CU", "out.citeulike-ui", "out.citeulike-ti", 1000)
    # generate_query_keywords("realworld", "CU", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "DV", "out.digg-votes", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "DV", "keywords_list.txt", 5, 10)

    # generate_dataset_with_keywords("realworld", "ML", "out.movielens-10m_ui", "out.movielens-10m_ti", 1000)
    # generate_query_keywords("realworld", "ML", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "SX", "out.escorts", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "SX", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "TA", "out.wang-tripadvisor", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "TA", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "UF", "out.opsahl-ucforum", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "UF", "keywords_list.txt", 5, 10)

    # generate_dataset_with_keywords("realworld", "VU", "out.pics_ui", "out.pics_ti", 1000)
    # generate_query_keywords("realworld", "VU", "keywords_list.txt", 5, 10)

    # generate_dataset("realworld", "WU", "out.munmun_twitterex_ut", "lognorm", 500, 3, 1000)
    # generate_query_keywords("realworld", "WU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dB"), "dBkU", "out.bd-25k", "uniform", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dB"), "dBkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dP"), "dPkU", "out.pl-25k", "uniform", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dB"), "dBkL", "out.bd-25k", "lognorm", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dB"), "dBkL", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dP"), "dPkL", "out.pl-25k", "lognorm", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dP"), "dPkL", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dB"), "dBkP", "out.bd-25k", "pareto", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dB"), "dBkP", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic", "dP"), "dPkP", "out.pl-25k", "pareto", 500, 3, 2000)
    # generate_query_keywords(os.path.join("synthetic", "dP"), "dPkP", "keywords_list.txt", 5, 10)

    # Param Size U
    # generate_dataset(os.path.join("synthetic-U10k", "dB"), "dBkL", "out.bd-U10k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U10k", "dP"), "dPkL", "out.pl-U10k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U10k", "dB"), "dBkP", "out.bd-U10k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U10k", "dP"), "dPkP", "out.pl-U10k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U10k", "dB"), "dBkU", "out.bd-U10k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U10k", "dP"), "dPkU", "out.pl-U10k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U10k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-U15k", "dB"), "dBkL", "out.bd-U15k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U15k", "dP"), "dPkL", "out.pl-U15k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U15k", "dB"), "dBkP", "out.bd-U15k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U15k", "dP"), "dPkP", "out.pl-U15k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U15k", "dB"), "dBkU", "out.bd-U15k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U15k", "dP"), "dPkU", "out.pl-U15k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U15k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-U50k", "dB"), "dBkL", "out.bd-U50k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U50k", "dP"), "dPkL", "out.pl-U50k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U50k", "dB"), "dBkP", "out.bd-U50k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U50k", "dP"), "dPkP", "out.pl-U50k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U50k", "dB"), "dBkU", "out.bd-U50k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U50k", "dP"), "dPkU", "out.pl-U50k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U50k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-U100k", "dB"), "dBkL", "out.bd-U100k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U100k", "dP"), "dPkL", "out.pl-U100k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U100k", "dB"), "dBkP", "out.bd-U100k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U100k", "dP"), "dPkP", "out.pl-U100k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U100k", "dB"), "dBkU", "out.bd-U100k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-U100k", "dP"), "dPkU", "out.pl-U100k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-U100k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # Param Size L
    # generate_dataset(os.path.join("synthetic-L10k", "dB"), "dBkL", "out.bd-L10k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L10k", "dP"), "dPkL", "out.pl-L10k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L10k", "dB"), "dBkP", "out.bd-L10k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L10k", "dP"), "dPkP", "out.pl-L10k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L10k", "dB"), "dBkU", "out.bd-L10k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L10k", "dP"), "dPkU", "out.pl-L10k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L10k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-L15k", "dB"), "dBkL", "out.bd-L15k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L15k", "dP"), "dPkL", "out.pl-L15k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L15k", "dB"), "dBkP", "out.bd-L15k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L15k", "dP"), "dPkP", "out.pl-L15k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L15k", "dB"), "dBkU", "out.bd-L15k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L15k", "dP"), "dPkU", "out.pl-L15k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L15k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-L50k", "dB"), "dBkL", "out.bd-L50k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L50k", "dP"), "dPkL", "out.pl-L50k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L50k", "dB"), "dBkP", "out.bd-L50k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L50k", "dP"), "dPkP", "out.pl-L50k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L50k", "dB"), "dBkU", "out.bd-L50k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L50k", "dP"), "dPkU", "out.pl-L50k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L50k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-L100k", "dB"), "dBkL", "out.bd-L100k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L100k", "dP"), "dPkL", "out.pl-L100k", "lognorm", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L100k", "dB"), "dBkP", "out.bd-L100k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L100k", "dP"), "dPkP", "out.pl-L100k", "pareto", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L100k", "dB"), "dBkU", "out.bd-L100k", "uniform", 500, 3, 1000)
    # generate_dataset(os.path.join("synthetic-L100k", "dP"), "dPkU", "out.pl-L100k", "uniform", 500, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-L100k", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # Param domain
    # generate_dataset(os.path.join("synthetic-25k-100", "dB"), "dBkL", "out.bd-25k", "lognorm", 100, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-100", "dP"), "dPkL", "out.pl-25k", "lognorm", 100, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-100", "dB"), "dBkP", "out.bd-25k", "pareto", 100, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-100", "dP"), "dPkP", "out.pl-25k", "pareto", 100, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-100", "dB"), "dBkU", "out.bd-25k", "uniform", 100, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-100", "dP"), "dPkU", "out.pl-25k", "uniform", 100, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-100", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-200", "dB"), "dBkL", "out.bd-25k", "lognorm", 200, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-200", "dP"), "dPkL", "out.pl-25k", "lognorm", 200, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-200", "dB"), "dBkP", "out.bd-25k", "pareto", 200, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-200", "dP"), "dPkP", "out.pl-25k", "pareto", 200, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-200", "dB"), "dBkU", "out.bd-25k", "uniform", 200, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-200", "dP"), "dPkU", "out.pl-25k", "uniform", 200, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-200", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-800", "dB"), "dBkL", "out.bd-25k", "lognorm", 800, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-800", "dP"), "dPkL", "out.pl-25k", "lognorm", 800, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-800", "dB"), "dBkP", "out.bd-25k", "pareto", 800, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-800", "dP"), "dPkP", "out.pl-25k", "pareto", 800, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-800", "dB"), "dBkU", "out.bd-25k", "uniform", 800, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-800", "dP"), "dPkU", "out.pl-25k", "uniform", 800, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-800", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-1000", "dB"), "dBkL", "out.bd-25k", "lognorm", 1000, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1000", "dP"), "dPkL", "out.pl-25k", "lognorm", 1000, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1000", "dB"), "dBkP", "out.bd-25k", "pareto", 1000, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1000", "dP"), "dPkP", "out.pl-25k", "pareto", 1000, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1000", "dB"), "dBkU", "out.bd-25k", "uniform", 1000, 3, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1000", "dP"), "dPkU", "out.pl-25k", "uniform", 1000, 3, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1000", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # Param W
    # generate_dataset(os.path.join("synthetic-25k-1", "dB"), "dBkL", "out.bd-25k", "lognorm", 500, 1, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1", "dP"), "dPkL", "out.pl-25k", "lognorm", 500, 1, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1", "dB"), "dBkP", "out.bd-25k", "pareto", 500, 1, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1", "dP"), "dPkP", "out.pl-25k", "pareto", 500, 1, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1", "dB"), "dBkU", "out.bd-25k", "uniform", 500, 1, 1000)
    # generate_dataset(os.path.join("synthetic-25k-1", "dP"), "dPkU", "out.pl-25k", "uniform", 500, 1, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-1", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-2", "dB"), "dBkL", "out.bd-25k", "lognorm", 500, 2, 1000)
    # generate_dataset(os.path.join("synthetic-25k-2", "dP"), "dPkL", "out.pl-25k", "lognorm", 500, 2, 1000)
    # generate_dataset(os.path.join("synthetic-25k-2", "dB"), "dBkP", "out.bd-25k", "pareto", 500, 2, 1000)
    # generate_dataset(os.path.join("synthetic-25k-2", "dP"), "dPkP", "out.pl-25k", "pareto", 500, 2, 1000)
    # generate_dataset(os.path.join("synthetic-25k-2", "dB"), "dBkU", "out.bd-25k", "uniform", 500, 2, 1000)
    # generate_dataset(os.path.join("synthetic-25k-2", "dP"), "dPkU", "out.pl-25k", "uniform", 500, 2, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-2", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-4", "dB"), "dBkL", "out.bd-25k", "lognorm", 500, 4, 1000)
    # generate_dataset(os.path.join("synthetic-25k-4", "dP"), "dPkL", "out.pl-25k", "lognorm", 500, 4, 1000)
    # generate_dataset(os.path.join("synthetic-25k-4", "dB"), "dBkP", "out.bd-25k", "pareto", 500, 4, 1000)
    # generate_dataset(os.path.join("synthetic-25k-4", "dP"), "dPkP", "out.pl-25k", "pareto", 500, 4, 1000)
    # generate_dataset(os.path.join("synthetic-25k-4", "dB"), "dBkU", "out.bd-25k", "uniform", 500, 4, 1000)
    # generate_dataset(os.path.join("synthetic-25k-4", "dP"), "dPkU", "out.pl-25k", "uniform", 500, 4, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-4", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    # generate_dataset(os.path.join("synthetic-25k-5", "dB"), "dBkL", "out.bd-25k", "lognorm", 500, 5, 1000)
    # generate_dataset(os.path.join("synthetic-25k-5", "dP"), "dPkL", "out.pl-25k", "lognorm", 500, 5, 1000)
    # generate_dataset(os.path.join("synthetic-25k-5", "dB"), "dBkP", "out.bd-25k", "pareto", 500, 5, 1000)
    # generate_dataset(os.path.join("synthetic-25k-5", "dP"), "dPkP", "out.pl-25k", "pareto", 500, 5, 1000)
    # generate_dataset(os.path.join("synthetic-25k-5", "dB"), "dBkU", "out.bd-25k", "uniform", 500, 5, 1000)
    # generate_dataset(os.path.join("synthetic-25k-5", "dP"), "dPkU", "out.pl-25k", "uniform", 500, 5, 1000)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dB"), "dBkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dP"), "dPkL", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dB"), "dBkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dP"), "dPkP", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dB"), "dBkU", "keywords_list.txt", 5, 10)
    # generate_query_keywords(os.path.join("synthetic-25k-5", "dP"), "dPkU", "keywords_list.txt", 5, 10)

    pass
