cd /home/yons/projects/CD-SBN/
# 10K, 15K, 25K, 50K, 100K
build/cdsbn -i dataset/synthetic-U10k/dB/dBkL/initial_graph.txt -l dataset/synthetic-U10k/dB/dBkL/label_list.txt -u dataset/synthetic-U10k/dB/dBkL/update_stream.txt -q dataset/synthetic-U10k/dB/dBkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U10k/dP/dPkL/initial_graph.txt -l dataset/synthetic-U10k/dP/dPkL/label_list.txt -u dataset/synthetic-U10k/dP/dPkL/update_stream.txt -q dataset/synthetic-U10k/dP/dPkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U10k/dB/dBkP/initial_graph.txt -l dataset/synthetic-U10k/dB/dBkP/label_list.txt -u dataset/synthetic-U10k/dB/dBkP/update_stream.txt -q dataset/synthetic-U10k/dB/dBkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U10k/dP/dPkP/initial_graph.txt -l dataset/synthetic-U10k/dP/dPkP/label_list.txt -u dataset/synthetic-U10k/dP/dPkP/update_stream.txt -q dataset/synthetic-U10k/dP/dPkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U10k/dB/dBkU/initial_graph.txt -l dataset/synthetic-U10k/dB/dBkU/label_list.txt -u dataset/synthetic-U10k/dB/dBkU/update_stream.txt -q dataset/synthetic-U10k/dB/dBkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U10k/dP/dPkU/initial_graph.txt -l dataset/synthetic-U10k/dP/dPkU/label_list.txt -u dataset/synthetic-U10k/dP/dPkU/update_stream.txt -q dataset/synthetic-U10k/dP/dPkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3

build/cdsbn -i dataset/synthetic-U15k/dB/dBkL/initial_graph.txt -l dataset/synthetic-U15k/dB/dBkL/label_list.txt -u dataset/synthetic-U15k/dB/dBkL/update_stream.txt -q dataset/synthetic-U15k/dB/dBkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U15k/dP/dPkL/initial_graph.txt -l dataset/synthetic-U15k/dP/dPkL/label_list.txt -u dataset/synthetic-U15k/dP/dPkL/update_stream.txt -q dataset/synthetic-U15k/dP/dPkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U15k/dB/dBkP/initial_graph.txt -l dataset/synthetic-U15k/dB/dBkP/label_list.txt -u dataset/synthetic-U15k/dB/dBkP/update_stream.txt -q dataset/synthetic-U15k/dB/dBkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U15k/dP/dPkP/initial_graph.txt -l dataset/synthetic-U15k/dP/dPkP/label_list.txt -u dataset/synthetic-U15k/dP/dPkP/update_stream.txt -q dataset/synthetic-U15k/dP/dPkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U15k/dB/dBkU/initial_graph.txt -l dataset/synthetic-U15k/dB/dBkU/label_list.txt -u dataset/synthetic-U15k/dB/dBkU/update_stream.txt -q dataset/synthetic-U15k/dB/dBkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U15k/dP/dPkU/initial_graph.txt -l dataset/synthetic-U15k/dP/dPkU/label_list.txt -u dataset/synthetic-U15k/dP/dPkU/update_stream.txt -q dataset/synthetic-U15k/dP/dPkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3

build/cdsbn -i dataset/synthetic-U50k/dB/dBkL/initial_graph.txt -l dataset/synthetic-U50k/dB/dBkL/label_list.txt -u dataset/synthetic-U50k/dB/dBkL/update_stream.txt -q dataset/synthetic-U50k/dB/dBkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U50k/dP/dPkL/initial_graph.txt -l dataset/synthetic-U50k/dP/dPkL/label_list.txt -u dataset/synthetic-U50k/dP/dPkL/update_stream.txt -q dataset/synthetic-U50k/dP/dPkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U50k/dB/dBkP/initial_graph.txt -l dataset/synthetic-U50k/dB/dBkP/label_list.txt -u dataset/synthetic-U50k/dB/dBkP/update_stream.txt -q dataset/synthetic-U50k/dB/dBkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U50k/dP/dPkP/initial_graph.txt -l dataset/synthetic-U50k/dP/dPkP/label_list.txt -u dataset/synthetic-U50k/dP/dPkP/update_stream.txt -q dataset/synthetic-U50k/dP/dPkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U50k/dB/dBkU/initial_graph.txt -l dataset/synthetic-U50k/dB/dBkU/label_list.txt -u dataset/synthetic-U50k/dB/dBkU/update_stream.txt -q dataset/synthetic-U50k/dB/dBkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U50k/dP/dPkU/initial_graph.txt -l dataset/synthetic-U50k/dP/dPkU/label_list.txt -u dataset/synthetic-U50k/dP/dPkU/update_stream.txt -q dataset/synthetic-U50k/dP/dPkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3

build/cdsbn -i dataset/synthetic-U100k/dB/dBkL/initial_graph.txt -l dataset/synthetic-U100k/dB/dBkL/label_list.txt -u dataset/synthetic-U100k/dB/dBkL/update_stream.txt -q dataset/synthetic-U100k/dB/dBkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U100k/dP/dPkL/initial_graph.txt -l dataset/synthetic-U100k/dP/dPkL/label_list.txt -u dataset/synthetic-U100k/dP/dPkL/update_stream.txt -q dataset/synthetic-U100k/dP/dPkL/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U100k/dB/dBkP/initial_graph.txt -l dataset/synthetic-U100k/dB/dBkP/label_list.txt -u dataset/synthetic-U100k/dB/dBkP/update_stream.txt -q dataset/synthetic-U100k/dB/dBkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U100k/dP/dPkP/initial_graph.txt -l dataset/synthetic-U100k/dP/dPkP/label_list.txt -u dataset/synthetic-U100k/dP/dPkP/update_stream.txt -q dataset/synthetic-U100k/dP/dPkP/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U100k/dB/dBkU/initial_graph.txt -l dataset/synthetic-U100k/dB/dBkU/label_list.txt -u dataset/synthetic-U100k/dB/dBkU/update_stream.txt -q dataset/synthetic-U100k/dB/dBkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
build/cdsbn -i dataset/synthetic-U100k/dP/dPkU/initial_graph.txt -l dataset/synthetic-U100k/dP/dPkU/label_list.txt -u dataset/synthetic-U100k/dP/dPkU/update_stream.txt -q dataset/synthetic-U100k/dP/dPkU/query_keywords_list-5.txt -t 0 -w 500 -k 4 -r 2 -s 3
